name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  # JOB 1 — Build senza test
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build senza test
        run: mvn -B clean install -DskipTests
        working-directory: ./unical-support-2


  # JOB 2 — Test con database
  
  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME}}
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      #Email template
      EMAIL_TEMPLATE_LOGO_URL: https://museo-multimediale-cosenza.s3.eu-north-1.amazonaws.com/logo.png

      # LLM config
      LLM_TIMEOUT_SECONDS: 30
      LLM_PROVIDER: gemini

      # Gemini config
      GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
      GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
      GEMINI_MODEL: gemini-2.5-flash
      GEMINI_BASE_URL: https://generativelanguage.googleapis.com
      GEMINI_EMBEDDING_MODEL: gemini-embedding-001

      # Groq config
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GROQ_MODEL: openai/gpt-oss-20b
      GROQ_BASE_URL: https://api.groq.com/openai/v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Esegui test
        run: mvn -B test
        working-directory: ./unical-support-2

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          retention-days: 30
